apiVersion: v1
kind: Service
metadata:
  name: accountserver-service
  labels:
    app: accountserver
spec:
  ports:
  - port: 80
    name: healthcheck
  - port: 1000
    name: grpc
  selector:
    app: accountserver
