apiVersion: v1
kind: Service
metadata:
  name: emailserver-service
  labels:
    app: emailserver
spec:
  ports:
  - port: 80
    name: healthcheck
  - port: 1000
    name: grpc
  selector:
    app: emailserver
