apiVersion: v1
kind: Service
metadata:
  name: faraday-service
  labels:
    app: faraday
spec:
  type: LoadBalancer
  loadBalancerIP: 104.198.99.93
  ports:
  - port: 80
  selector:
    app: faraday
