apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/app-mysql-pv
