apiVersion: v1
kind: Service
metadata:
  name: faraday-service
  labels:
    app: faraday
spec:
  type: NodePort
  clusterIP: 10.0.0.99
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: faraday